=== UniverityOfWashingtonLibrariesSchemas/schemasProject/original/schema-4-dds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://faculty.washington.edu/tgis/xml/xsd"
    xmlns="http://faculty.washington.edu/tgis/xml/xsd">

    <!-- Note from TG, 2015-12-10: I attempted to make the default namespace
    http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries
    but that made my references to global types unusable, I'm not sure why.
    This can be resolved at a future date; for no I've fallen back to noNamespace.
    -->
    
    <!--
       This schema needs mechanisms to map properties to RDF properties
       for use in producing an ontology;
       we will need a property to map to already existing web resources
       anther to map to a nonexistent property, or indicate that a search should be done
       and another when we establish a local web resource to serve as a property.
    -->

    <xs:annotation>
        <xs:documentation> This is a schema to validate MIG data dictionaries. The MIG data
            dictionaries were written to CONTENTdm collection configurations and metadata input. The
            official version of those data dictionaries are posted at
            http://www.lib.washington.edu/msd/pubcat/mig/datadicts. MIG maintains a source XML file
            for selected data dictionaries (as of 2015-12-10), which is an XML file that can be
            validated using this schema. </xs:documentation>
    </xs:annotation>

    <xs:element name="migDataDictionary" type="ddType"/>

    <xs:complexType name="ddType">
        <xs:sequence>
            <xs:element name="ddName"/>
            <xs:element name="ddPartOfProject"/>
            <xs:element name="latestUpdate"/>
            <xs:element name="metadataLiaisons">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="metadataLiaison" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cdmCo" type="yesNo"/>
            <!-- Element for recording whether or not CONTENTdm compound objects are permitted -->
            <xs:element name="standalone" type="yesNo"/>
            <!-- Element for recording whether or not CONTENTdm compound objects are permitted -->
            <!-- Needed to state whether standalone can co-exist with compound objects -->
            <xs:element name="properties">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="property" type="propertyType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="year" type="xs:gYear"/>
        <xs:attribute name="id" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="cdmLabel" type="xs:string"/>
            <!-- Element for the custom CONTENTdm field name -->
            <xs:element name="cdm-dc-label" type="cdm-qdc"/>
            <!-- CONTENTdm's label for the equivalent Dublin Core field; usually slightly different than DCMI's label -->
            <xs:element name="dc" type="dcterms"/>
            <!-- DCMI's official label for the equivalent Dublin Core property -->
            <xs:element name="cdmDatatype" type="cdmDatatype"/>
            <!-- The data type for CONTENTdm -->
            <xs:element name="cdmLarge" type="yesNo"/>
            <!-- The CONTENTdm text box size as it will appear in the CONTENTdm Admon Module-->
            <xs:element name="searchable" type="yesNo"/>
            <!-- Element for recording whether or not value will be indexed by CONTENTdm -->
            <xs:element name="hidden" type="yesNo"/>
            <!-- Element for recording whether or not CONTNETdm will display the element/value to the public -->
            <xs:element name="required" type="yesNo"/>
            <!-- Element for recording whether or not element value is required  -->
            <xs:element name="cdmControlledVocab" type="yesNo"/>
            <!-- Element for recording whether or not element is a CONTENTdm controlled vocabulary, thus enabling phrase indexing  -->
            <!-- THE FOLLOWING ARE NOT NEEDED:
            <xs:element name="coObject" type="yesNo"/>
            <xs:element name="coItem" type="yesNo"/>
            <xs:element name="stand" type="yesNo"/>
            -->
            <xs:element name="description" type="para"/>
            <!-- Element to describe a property used to describe a CONTENTdm standalone object (i.e. item described is ~not~ a compound object). -->
            <!-- Required for all properties used to describe standalone objects. -->
            <xs:element name="examples" type="para" minOccurs="0"/>
            <!-- Element for providing examples of the use of a property describing a CONTENTdm standalone object. -->
            <xs:element name="descriptionCoObject" type="para"/>
            <!-- Element to describe a property used to describe a CONTENTdm compound object at the full object level. -->
            <!-- Required for all properties used to describe CONTENTdm compound objects. -->
            <xs:element name="examplesCoObject" type="para" minOccurs="0"/>
            <!-- Element for providing examples of the use of a property describing a CONTENTdm compound object at the full object level. -->
            <xs:element name="descriptionCoItem" type="para"/>
            <!-- Element to describe a property used to describe a CONTENTdm compound object at the item or "page" level. -->
            <!-- Required for all properties used to describe CONTENTdm compound objects. -->
            <xs:element name="examplesCoItem" type="para" minOccurs="0"/>
            <!-- Element for providing examples of the use of a property describing a CONTENTdm compound object at the item or "page" level. -->
            <xs:element name="admin" type="para" minOccurs="0"/>
            <!-- Element for recording staff-only information to help adminster the property -->
            <xs:element name="generalNotes" type="para" minOccurs="0"/>
            <!-- Element for recording staff-only information hat further describes the propery -->
            <xs:element name="dcgMarcMapping" minOccurs="0"/>
            <!-- Element for mapping the property to MARC -->
            <xs:element name="marcNotes" minOccurs="0"/>
            <!-- Element to describe difficulties in mapping the property to MARC -->
        </xs:sequence>
        <xs:attribute name="oid" type="xs:ID"/>
        <xs:attribute name="iid" type="xs:integer"/>
    </xs:complexType>

    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cdmDatatype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="para">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="cdm-qdc">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Accrual Method"/>
            <xs:enumeration value="Accrual Periodicity"/>
            <xs:enumeration value="Accrual Policy"/>
            <xs:enumeration value="Audience"/>
            <xs:enumeration value="Audience-Education Level"/>
            <xs:enumeration value="Audience-Mediator"/>
            <xs:enumeration value="Contributors"/>
            <xs:enumeration value="Coverage"/>
            <xs:enumeration value="Coverage-Spatial"/>
            <xs:enumeration value="Coverage-Temporal"/>
            <xs:enumeration value="Creator"/>
            <xs:enumeration value="Date"/>
            <xs:enumeration value="Date-Accepted"/>
            <xs:enumeration value="Date-Available"/>
            <xs:enumeration value="Date-Copyrighted"/>
            <xs:enumeration value="Date-Created"/>
            <xs:enumeration value="Date-Issued"/>
            <xs:enumeration value="Date-Modified"/>
            <xs:enumeration value="Date-Submitted"/>
            <xs:enumeration value="Date-Valid"/>
            <xs:enumeration value="Description"/>
            <xs:enumeration value="Description-Abstract"/>
            <xs:enumeration value="Description-Table Of Contents"/>
            <xs:enumeration value="Format"/>
            <xs:enumeration value="Format-Extent"/>
            <xs:enumeration value="Format-Medium"/>
            <xs:enumeration value="Identifier"/>
            <xs:enumeration value="Identifier-Bibliographic Citation"/>
            <xs:enumeration value="Instructional Method"/>
            <xs:enumeration value="Language"/>
            <xs:enumeration value="None"/>
            <xs:enumeration value="Provenance"/>
            <xs:enumeration value="Publisher"/>
            <xs:enumeration value="Relation"/>
            <xs:enumeration value="Relation-Conforms To"/>
            <xs:enumeration value="Relation-Has Format Of"/>
            <xs:enumeration value="Relation-Has Part"/>
            <xs:enumeration value="Relation-Has Version"/>
            <xs:enumeration value="Relation-Is Format Of"/>
            <xs:enumeration value="Relation-Is Part Of"/>
            <xs:enumeration value="Relation-Is Referenced By"/>
            <xs:enumeration value="Relation-Is Replaced By"/>
            <xs:enumeration value="Relation-Is Required By"/>
            <xs:enumeration value="Relation-Is Version Of"/>
            <xs:enumeration value="Relation-References"/>
            <xs:enumeration value="Relation-Replaces"/>
            <xs:enumeration value="Relation-Requires"/>
            <xs:enumeration value="Rights"/>
            <xs:enumeration value="Rights-Access Rights"/>
            <xs:enumeration value="Rights-License"/>
            <xs:enumeration value="Rights-Rights Holder"/>
            <xs:enumeration value="Source"/>
            <xs:enumeration value="Subject"/>
            <xs:enumeration value="Title"/>
            <xs:enumeration value="Title-Alternative"/>
            <xs:enumeration value="Type"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/original/rubbings-dd.xml
<?xml version="1.0" encoding="UTF-8"?>
<migDataDictionary xmlns="http://faculty.washington.edu/tgis/xml/xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://faculty.washington.edu/tgis/xml/xsd schema-4-dds.xsd">
    <ddName>University of Washington East Asia Library Digital Chinese Rubbings Collection</ddName>
    <ddPartOfProject/>
    <latestUpdate>October 11, 2016</latestUpdate>
    <metadataLiaisons>
        <metadataLiaison>Theodore Gerontakos, Ann Lally, Zhijia Shen</metadataLiaison>
    </metadataLiaisons>
    <cdmCo>no</cdmCo>
    <standalone>yes</standalone>
    <properties>
        <property>
            <cdmLabel>Title</cdmLabel>
            <cdm-dc-label>Title</cdm-dc-label>
            <dc>title</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>no</hidden>
            <required>yes</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter transcribed title or formulate a title. This title should be in English.</para>
            </description>
            <examples>
                <para>Scroll prints with Xu Zhang’s cursive calligraphy</para>
                <para>	Wuliang Shrine, North Wuzhaishan Village, Jiaxiang County, Jining City, Shandong Province, China</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
        </property>
        <property>
            <cdmLabel>[Title-Chinese-Label undecided, see admin notes]</cdmLabel>
            <cdm-dc-label>Title-Alternative</cdm-dc-label>
            <dc>alternative</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>no</hidden>
            <required>yes</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter transcribed title or formulate a title. This title should be in Chinese.</para>
            </description>
            <examples>
                <para>張旭草書拓本</para>
                <para>韓寄生造像記</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Undecided on Chinese field label.</para>
                <para>學名</para>
                <para>題名</para>
            </admin>
        </property>
        <property>
            <cdmLabel>[Title-Romanized]</cdmLabel>
            <cdm-dc-label>Title-Alternative</cdm-dc-label>
            <dc>alternative</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>yes</hidden>
            <required>no</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Romanize Chinese title using the appropriate ALA-LC Romanization Table.</para>
            </description>
            <examples>
                <para>Han Chi-sheng tsao hsiang chi</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Not sure we want this field. If we do, where else do we want romanization?</para>
            </admin>
        </property>
        <property>
            <cdmLabel>Original Creator</cdmLabel>
            <cdm-dc-label>Creator</cdm-dc-label>
            <dc>creator</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>no</hidden>
            <required>no</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter name of the creator of the original.</para>
                <para>Enter the value in English.</para>
                <para>If there are multiple creators, separate each creator with a semi-colon + space.</para>
            </description>
            <examples>
                <para>Huai-su (725-85)</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Will the creator usually be an author? Maybe an artist? Should we have more than one field with custom labels for each type of creator?</para>
                <para>Other possibilities for "agents:" author/creator-or-contributor, calligrapher/creator-or-contributor, inscriber/creator-or-contributor, collector/contributor, rubbing maker/contributor</para>
            </admin>
        </property>
        <property>
            <cdmLabel>[Original Creator-Chinese]</cdmLabel>
            <cdm-dc-label>Creator</cdm-dc-label>
            <dc>creator</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>no</hidden>
            <required>no</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter name of the creator of the original.</para>
                <para>Enter the value in English.</para>
                <para>If there are multiple creators, separate each creator with a semi-colon + space.</para>
            </description>
            <examples>
                <para>懷素</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Undecided on Chinese field label.</para>
                <para>作者</para>
                <para>撰文㆟</para>
                <para>创造者</para>
            </admin>
        </property>
        <property>
            <cdmLabel>[Original Creator-romanized]</cdmLabel>
            <cdm-dc-label>Creator</cdm-dc-label>
            <dc>creator</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>yes</hidden>
            <required>no</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Romanize Chinese title using the appropriate ALA-LC Romanization Table.</para>
            </description>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Do we want this field? Is the name in "English" really a romanized version?</para>
            </admin>
        </property>
        <property>
            <cdmLabel>Date of Original</cdmLabel>
            <cdm-dc-label>Date-Created</cdm-dc-label>
            <dc>created</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>no</searchable>
            <hidden>no</hidden>
            <required>yes</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter date the original artifact was created (if known).</para>
                <para>	
                Enter date or date range for all items.</para>
                <para>This is the display field. Enter first the day if available, then the month</para>
            </description>
            <examples>
                <para>23 April 2001</para>
                <para>October-November 2006</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Required if creation date is unknown.</para>
                <para>Throughout the data dictionary, do we want to refer to the original artifact as "The original?"</para>
            </admin>
        </property>
        <property>
            <cdmLabel>[Date of Original with Chinese label]</cdmLabel>
            <cdm-dc-label>Date-Created</cdm-dc-label>
            <dc>created</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>no</searchable>
            <hidden>no</hidden>
            <required>yes</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter date the original artifact was created (if known).</para>
                <para>	
                Enter date or date range for all items.</para>
                <para>This is the display field. Enter first the day if available, then the month</para>
            </description>
            <examples>
                <para>23 April 2001</para>
                <para>October-November 2006</para>
            </examples>
            <descriptionCoObject/>
            <descriptionCoItem/>
            <admin>
                <para>Required if creation date is unknown.</para>
                <para>The value of this field is the same as "Date of original." The only difference between that field and this is the name of the field (i.e. the label). We could combine into one field with a bilingual label, if preferred.</para>
                <para>Not sure what the field name will be.</para>
                <para>年代</para>
                <para>Please note only date types following the Gregorian Calendar are expected in our date fields; we have no date fields that expect dates using other systems.</para>
            </admin>
        </property>
        <property>
            <cdmLabel>DatesOfOriginal</cdmLabel>
            <cdm-dc-label>None</cdm-dc-label>
            <dc>none</dc>
            <cdmDatatype>text</cdmDatatype>
            <cdmLarge>no</cdmLarge>
            <searchable>yes</searchable>
            <hidden>yes</hidden>
            <required>yes</required>
            <cdmControlledVocab>no</cdmControlledVocab>
            <description>
                <para>Enter year only.</para>
                <para>Separate additional years, even if sequential, with comma.</para>
                <para>Approximate dates should include five years on either side.</para>
