=== UniverityOfWashingtonLibrariesSchemas/schemasProject/xsd4md/schema-4-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md">
    
    <!-- vresion 0.1 2017-07-26 -->

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    
    <xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:annotation>
        <xs:documentation>Schema to validate properties used by UW Libraries.</xs:documentation>
    </xs:annotation>

    <xs:element name="property" type="propertyType">
    </xs:element>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="required" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>

    <!-- We'll want an enumeration of DSpace properties for use with the dspaceProperty element -->
    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Note on "admin:"
     any info to help administer the metadata;
     inputting assistance goes in desciptions/instructions;
     further assistance "understanding" the metadata: "generalNotes"-->
    <xs:complexType name="additionalInfoType">
        <xs:sequence>
            <!-- Originally thought 2 elements needed in this sequence;
                 as work progressed, it seemed one was better;
                 recommended: do not use <admin>, use <generalNotes> ;
                 both will be retained to validate legacy data;
                 XSLTs should output both elements as if they were the same-->
            <xs:element name="admin" type="paraType4co" minOccurs="0"/>
            <xs:element name="generalNotes" type="paraType4co" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="marcType">
        <xs:sequence>
            <xs:element name="dcgMarcMapping" type="dcgType"/>
            <xs:element name="dcgNotes" type="paraType" minOccurs="0"/>
            <xs:element name="marcNotes" type="paraType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dcgType">
        <xs:sequence>
            <xs:element name="field" type="xs:integer" minOccurs="0"/>
            <xs:element name="subfield" type="xs:string" minOccurs="0"/>
            <xs:element name="indicators" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="xsdType">
        <xs:sequence>
            <xs:element name="typeAttribute" type="xs:QName" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="simpleType" type="xs:localSimpleType" minOccurs="0"/>
            <xs:element name="complexType" type="xs:localComplexType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="simpleTypeType">
        <xs:sequence>
            <xs:element name="pattern" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

   <!-- might need other properties in addition to sameAs
        like maybe skos:exactMatch, etc.
   -->
    <xs:complexType name="rdfType">
        <xs:sequence>
            <xs:element name="sameAs" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element name="dateCreated">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="single" type="xs:date"/>
                        <xs:element name="range">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="start" type="xs:date"/>
                                    <xs:element name="end" type="xs:date"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="created4Coll" type="xs:string"/>
            <!-- justification needs to be a type=para -->
            <xs:element name="justification" type="xs:string"/>
            <xs:element name="changeLog">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="change">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="date" type="xs:date"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <xs:enumeration value="cdmAdministrative"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paraType4co">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="no"/>
                    <xs:enumeration value="object"/>
                    <xs:enumeration value="item"/>
                <!-- the following 3 types of COs eliminated 2017-06-29;
                     we may want them for generalNotes however:
                    <xs:enumeration value="objectAndStandalone"/>
                    <xs:enumeration value="itemAndStandalone/"/>
                    <xs:enumeration value="coAll"/>-->
                    <xs:enumeration value="all"/>
                    <xs:enumeration value="agnostic"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- below global attribute does not seem necessary
    <xs:attribute name="co">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="no"/>
                <xs:enumeration value="object"/>
                <xs:enumeration value="item"/>
                <xs:enumeration value="coAll"/>
                <xs:enumeration value="all"/>
                <xs:enumeration value="agnostic"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    -->

    <xs:element name="customization" type="custParaType"/>

    <xs:complexType name="custParaType">
        <xs:complexContent>
            <xs:extension base="paraType4co">
                <xs:attribute name="dd" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="exPara"/>

</xs:schema>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/language.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd"><uid>p50</uid><labels>
      <platformIndependent>language</platformIndependent>
      <dc>language</dc>
   </labels><uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired><cdm>
      <label>Language</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm><dspace>
      <dspaceProperty/>
   </dspace><descriptions>
      <definition>
         <para>A language of the resource.</para>
      </definition>
      <instructions co="object">
         <para>Name of language(s) used in the interview fully spelled out.</para>
      </instructions>
   </descriptions><examples>
      <example co="object">
         <para>English</para>
         <para>Spanish</para>
      </example>
   </examples><additionalInfo>
      <admin co="object"/>
   </additionalInfo><marc>
      <dcgMarcMapping/>
      <marcNotes/>
   </marc><xsd>
      <typeInfo level="object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd><rdf>
      <sameAs/>
   </rdf><history>
      <dateCreated>
         <single>2018-03-26</single>
      </dateCreated>
      <created4Coll>University of Washington Tacoma Oral Histories</created4Coll>
      <justification>MIG requested this field for UWT Oral Histories, allowing language to be indexed, as we do with other oral histories.</justification>
      <changeLog>
         <change/>
      </changeLog>
   </history></property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/digitalReproductionInformation.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
    <labels>
        <platformIndependent>digitalReproductionInformation</platformIndependent>
        <dc>format</dc>
    </labels>
    <cdm>
        <label>Digital Reproduction Information</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>no</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired><uwRequired>no</uwRequired>
        <cdmControlledVocab>no</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty/>
    </dspace>
    <descriptions>
        <definition>
            <para>Describes the digital conversion process, date scanned, etc.</para>
        </definition>
        <instructions co="no">
            <para>Input a paragraph with pertinent information on the digital conversion process.</para>
        </instructions>
        <instructions co="object">
            <para>Input a paragraph with pertinent information on the digital conversion process of the overall object.</para>
        </instructions>
    </descriptions>
    <examples>
        <example co="no">
            <para>Scanned from a photographic print using a Microtek Scanmaker 9600XL at 72 dpi in JPEG format at compression rate 3.      10/1998.</para>
        </example>
      <example co="object">
          <para>Scanned from original text or image at 400 dpi saved in TIFF format, resized and enhanced using Adobe Photoshop, and imported as JPEG2000 using Contentdm software's JPEG2000 Extension. 2006.</para>
      </example>
    </examples>
    <additionalInfo/>
    <marc>
        <dcgMarcMapping/>
        <marcNotes>
            <para/>
        </marcNotes>
    </marc>
    <xsd>
        <typeAttribute>xs:string</typeAttribute>
        <complexType/>
    </xsd>
    <rdf>
        <sameAs/>
    </rdf>
    <history>
        <dateCreated>
            
            <range>
                <start>2000-01-01</start>
                <end>2017-01-12</end>
            </range>
        </dateCreated>
        <created4Coll>Special Collections Photograph Collections</created4Coll>
        <justification>Special Collections wanted a description of the digitization process.</justification>
        <changeLog>
            <change/><change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
        </changeLog>
    </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/notes.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd"><uid>p55</uid><labels>
      <platformIndependent>notes</platformIndependent>
      <dc>description</dc>
   </labels><uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired><cdm>
      <label>Notes</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>yes</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm><dspace>
      <dspaceProperty/>
   </dspace><descriptions>
      <definition>
         <para>An account of the resource.</para>
      </definition>
      <instructions co="no">
         <para>Enter any information of importance that is not represented elsewhere.</para>
         <para>Each separate "note" should be a paragraph. Additional notes can be added, separated from the previous note using a blank line.</para>
      </instructions>
      <instructions co="object">
         <para>Enter any information of importance that is not represented elsewhere.</para>
         <para>Each separate "note" should be a paragraph. Additional notes can be added, separated from the previous note using a blank line.</para>
      </instructions>
      <customization co="no" dd="ac">
         <para>An account of the drawing.</para>
         <para>Notes include any information of importance that is not represented elsewhere.</para>
      </customization>
      <customization co="object" dd="uwtoh">
         <para>Enter any descriptive narrative information of importance about the project and its subjects that is not recorded elsewhere.</para>
         <para>Each separate "note" should be a paragraph. Additional notes can be added, separated from the previous note using a blank line.</para>
      </customization>
   </descriptions><examples>
      <example co="no">
         <para>Photographs taken by Asahel Curtis during his trip to the Klondike in 1897-1899.</para>
         <para>Caption on image: Curtis 319.</para>
         <para>Handwritten on verso: Mrs. McLain with dog team.</para>
         <para>PH Coll 519.319</para>
      </example>
      <example co="object">
         <para>Photographs taken by Asahel Curtis during his trip to the Klondike in 1897-1899.</para>
         <para>Caption on image: Curtis 319.</para>
         <para>Handwritten on verso: Mrs. McLain with dog team.</para>
         <para>PH Coll 519.319</para>
      </example>
      <customization co="no" dd="ac">
         <para>Handwritten in title block: Apartment house. Osborn, Architect. 325 Leary Bldg., Seattle, Wash. E.C.R. [drawn by?]</para>
         <para>Handwritten beneath drawing: First floor plan. Scale: 1/16" to 1'</para>
         <para>Plans for a frame hotel to be erected by the Lake View Land Co. at Lakeview, Wash.</para>
         <para>Stamped on cover sheet: Farrell and Darmer, Architects, Tacoma, Wash. Ter.</para>
         <para>From inventory: (1890)</para>
         <para>Residence for Mr. C.J. Lord</para>
         <para>Written in title block: Residence for Mr. C.J. Lord; 21st and Columbia Streets, Olympia, Washington; Basement and Foundation plan; Joseph H. Wohleb, Architect. Olympia, Wash.; Drawn by Y.D.W.; Traced by W.W.; Date Feb. 1923;Comm. No. 251; Sheet no. 2; Scale: 1/4" to 1'</para>
      </customization>
      <customization co="object" dd="uwtoh">
         <para>The oral history interview with Michal Sullivan was part of the “Founding Stories” phase of the UW Tacoma Oral History Project.
         </para>
      </customization>
   </examples><additionalInfo>
      <generalNotes co="all">
         <para>"Notes" is distingushed from "Historical Notes" mainly because it descibes the image/resource only. Values in this field also may be considered more "indexable" insofar as they precisely descibe the image/resource. "HistoricalNotes" are more like "writing" and create a broad historical context.</para>
      </generalNotes>
   </additionalInfo><marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc><xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd><rdf>
      <cdmRdf>
         <dpla>
            <map xml:lang="en">dct:description</map>
            <object>literal</object>
            <class>SourceResource</class>
            <process>cleanNotes</process>
            <node/>
         </dpla>
      </cdmRdf>
   </rdf><history>
      <dateCreated>
         <range>
            <start>2000-01-01</start>
            <end>2017-01-06</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Photograph Collections</created4Coll>
      <justification>Needed a place to enter all "other" information valuable to the description of the resource.</justification>
      <changeLog>
         <change/>
         <change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
         <change date="2018-02-27">Added customization for Architecture of the Pacific Northwest.</change>
      </changeLog>
   </history></property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/cataloging.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
   <labels>
      <platformIndependent>cataloging</platformIndependent>
      <dc>none</dc>
   </labels>
   <uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Cataloging</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>yes</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>[Unknown.]</para>
      </definition>
      <instructions co="no">
         <para>[Unknown.]</para>
      </instructions>
      <instructions co="object">
         <para>[Unknown.]</para>
      </instructions>
   </descriptions>
   <examples>
      <example co="no">
         <para>[none]</para>
      </example>
      <example co="object">
         <para>[none]</para>
      </example>
   </examples>
   <additionalInfo>
      <admin co="all">
         <para>Unique to ayp? No, also in Civil War Letters, but there are no values in Civil War.</para>
         <para>Does output using Cdm export.</para>
         <para>Did not appear in DI/ITS output when all collections were output.</para>
         <para>Delete this property?</para>
      </admin>
   </additionalInfo>
   <marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc>
   <xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd>
   <rdf>
      <sameAs/>
   </rdf>
   <history>
      <dateCreated>
         <range>
            <start>2000-01-01</start>
            <end>2017-02-22</end>
         </range>
      </dateCreated>
      <created4Coll>ayp</created4Coll>
      <justification>[unknown]</justification>
      <changeLog>
         <change/>
         <change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
      </changeLog>
   </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/alternativeTitle.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd"><uid>p2</uid><labels>
      <platformIndependent>alternativeTitle</platformIndependent>
      <dc>alternative</dc>
   </labels><uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired><cdm>
      <label>Alternative Title</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm><dspace>
      <dspaceProperty/>
   </dspace><descriptions>
      <definition>
         <para>An alternative name for the resource.</para>
      </definition>
      <instructions co="no">
         <para>Enter an alternative title; may or may not follow instructions for entering titles.</para>
         <para>When applicable, add a note in the Notes field describing the source of the alternative title.</para>
      </instructions>
   </descriptions><examples>
      <example co="no">
         <para>Century 21 Restaurant and Observation Tower</para>
         <para>Wu Building</para>
      </example>
      <customization co="no"/>
   </examples><additionalInfo/><marc>
      <dcgMarcMapping>
         
      </dcgMarcMapping>
      <dcgNotes>
         
      </dcgNotes>
      <marcNotes/>
   </marc><xsd>
      <typeInfo level="standalone">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd><rdf>
      <sameAs/>
   </rdf><history>
      <dateCreated>
         <range>
            <start>2006-01-01</start>
            <end>2018-02-20</end>
         </range>
      </dateCreated>
      <created4Coll>Architecture of the Pacific Northwest</created4Coll>
      <justification>Alternative titles are often needed on the digital collections.</justification>
      <changeLog>
         <change/>
         
      </changeLog>
   </history></property>
