=== UniverityOfWashingtonLibrariesSchemas/schemasProject/xsd4md/schema-4-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md">
    
    <!-- vresion 0.1 2017-07-26 -->

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    
    <xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:annotation>
        <xs:documentation>Schema to validate properties used by UW Libraries.</xs:documentation>
    </xs:annotation>

    <xs:element name="property" type="propertyType">
    </xs:element>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="required" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>

    <!-- We'll want an enumeration of DSpace properties for use with the dspaceProperty element -->
    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Note on "admin:"
     any info to help administer the metadata;
     inputting assistance goes in desciptions/instructions;
     further assistance "understanding" the metadata: "generalNotes"-->
    <xs:complexType name="additionalInfoType">
        <xs:sequence>
            <!-- Originally thought 2 elements needed in this sequence;
                 as work progressed, it seemed one was better;
                 recommended: do not use <admin>, use <generalNotes> ;
                 both will be retained to validate legacy data;
                 XSLTs should output both elements as if they were the same-->
            <xs:element name="admin" type="paraType4co" minOccurs="0"/>
            <xs:element name="generalNotes" type="paraType4co" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="marcType">
        <xs:sequence>
            <xs:element name="dcgMarcMapping" type="dcgType"/>
            <xs:element name="dcgNotes" type="paraType" minOccurs="0"/>
            <xs:element name="marcNotes" type="paraType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dcgType">
        <xs:sequence>
            <xs:element name="field" type="xs:integer" minOccurs="0"/>
            <xs:element name="subfield" type="xs:string" minOccurs="0"/>
            <xs:element name="indicators" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="xsdType">
        <xs:sequence>
            <xs:element name="typeAttribute" type="xs:QName" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="simpleType" type="xs:localSimpleType" minOccurs="0"/>
            <xs:element name="complexType" type="xs:localComplexType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="simpleTypeType">
        <xs:sequence>
            <xs:element name="pattern" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

   <!-- might need other properties in addition to sameAs
        like maybe skos:exactMatch, etc.
   -->
    <xs:complexType name="rdfType">
        <xs:sequence>
            <xs:element name="sameAs" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element name="dateCreated">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="single" type="xs:date"/>
                        <xs:element name="range">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="start" type="xs:date"/>
                                    <xs:element name="end" type="xs:date"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="created4Coll" type="xs:string"/>
            <!-- justification needs to be a type=para -->
            <xs:element name="justification" type="xs:string"/>
            <xs:element name="changeLog">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="change">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="date" type="xs:date"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <xs:enumeration value="cdmAdministrative"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paraType4co">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="no"/>
                    <xs:enumeration value="object"/>
                    <xs:enumeration value="item"/>
                <!-- the following 3 types of COs eliminated 2017-06-29;
                     we may want them for generalNotes however:
                    <xs:enumeration value="objectAndStandalone"/>
                    <xs:enumeration value="itemAndStandalone/"/>
                    <xs:enumeration value="coAll"/>-->
                    <xs:enumeration value="all"/>
                    <xs:enumeration value="agnostic"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- below global attribute does not seem necessary
    <xs:attribute name="co">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="no"/>
                <xs:enumeration value="object"/>
                <xs:enumeration value="item"/>
                <xs:enumeration value="coAll"/>
                <xs:enumeration value="all"/>
                <xs:enumeration value="agnostic"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    -->

    <xs:element name="customization" type="custParaType"/>

    <xs:complexType name="custParaType">
        <xs:complexContent>
            <xs:extension base="paraType4co">
                <xs:attribute name="dd" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="exPara"/>

</xs:schema>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/publisherLocation.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md 
    http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
    <uid>p120</uid>
    <labels>
        <platformIndependent>publisherLocation</platformIndependent>
        <dc>none</dc>
    </labels>
    <uwRequired>
        <uwStandalone>no</uwStandalone>
        <uwObject>no</uwObject>
        <uwItem>no</uwItem>
    </uwRequired>
    <cdm>
        <label>Publisher Location</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>yes</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <cdmControlledVocab>yes</cdmControlledVocab>
    </cdm>
    <!-- omit dspace -->
    <dspace>
        <dspaceProperty/>
    </dspace>
    <descriptions>
        <definition>
            <para>A location, usually a city, associated with the publisher of the resource.</para>
        </definition>
        <customization co="object" dd="p16786coll3">
            <para>Search for the publisher's geographic location in the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov.</para>
            <para>If a match is found, copy the name string for use just as it appears at the top of the page, above the URI(s). Include any parenthesis following the location name.</para>
            <para>If no record exists, use the most universal spelling of the location.</para>
            <para>If multiple publishers are associated with a resource, include the Publisher value to which the location applies in square brackets ("[" and "]") following this value.</para>
            <para>If entering multiple values for this property, separate each using a semicolon and space (“; “). Order of values does not matter.</para>
        </customization>
        <customization co="no" dd="p16786coll3">
            <para>Search for the publisher's geographic location in the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov.</para>
            <para>If a match is found, copy the name string for use just as it appears at the top of the page, above the URI(s). Include any parenthesis following the location name.</para>
            <para>If no record exists, use the most universal spelling of the location.</para>
            <para>If multiple publishers are associated with a resource, include the Publisher value to which the location applies in square brackets ("[" and "]") following this value.</para>
            <para>If entering multiple values for this property, separate each using a semicolon and space (“; “). Order of values does not matter.</para>
        </customization>
    </descriptions>
    <examples>
        <example co="object">
            <para>İzmir (Turkey)</para>
            <para>Jerusalem [Cherezli, Salomon Israel]; Istanbul (Turkey) [Joseph, Benjamin Ben]</para>
        </example>
        <example co="no">
            <para>İzmir (Turkey)</para>
            <para>Jerusalem [Cherezli, Salomon Israel]; Istanbul (Turkey) [Joseph, Benjamin Ben]</para>
        </example>
    </examples>
    <additionalInfo/>
    <marc>
        <dcgMarcMapping/>
    </marc>
    <xsd/>
    <rdf/>
    <!-- Omit:
        additionalInfo
        marc -->
    <!-- BMR TO DO - XSD -->
    <!-- Omit:
        rdf
        cdmRdf -->
    <history>
        <dateCreated>
            <single>2021-03-20</single>
        </dateCreated>
        <created4Coll>Sephardic Studies Digital Collection (p16786coll3)</created4Coll>
        <justification>SSDC requires a property to provide publisher-location values.</justification>
        <changeLog>
            <change/>
        </changeLog>
    </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/formerOwner.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md 
    http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
    <uid>p127</uid>
    <labels>
        <platformIndependent>formerOwner</platformIndependent>
        <dc>none</dc>
    </labels>
    <uwRequired>
        <uwStandalone>no</uwStandalone>
        <uwObject>no</uwObject>
        <uwItem>no</uwItem>
    </uwRequired>
    <cdm>
        <label>Former Owner</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>yes</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <cdmControlledVocab>yes</cdmControlledVocab>
    </cdm>
    <!-- omit dspace -->
    <dspace>
        <dspaceProperty/>
    </dspace>
    <descriptions>
        <definition>
            <para>A person or corporate body who previously owned the physical item.</para>
        </definition>
        <customization co="object" dd="p16786coll3">
            <para>When searching for donor or lender in Sephardic Studies Collection Master Catalog, some contributions will be recorded as "Person A via Person B." In that case, Person A is the former owner, and their name belongs in this field.</para>
            <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov for the lender name.</para>
            <para>If a potential match is found, confirm that it is the person associated with the resource: it may be helpful to review information included in the web display such as source(s) of information and occupation (for persons), and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
            <para>Copy the name string for use just as it appears at the top of the page, above the URI(s), including dates.</para>
            <para>If no record exists, record personal names as "Lastname, Firstname".</para>
            <para>For a personal name like Alexander Ben Guiat, "Ben" is considered part of the first name and is transcribed as: "Guiat, Alexander Ben".</para>
            <para>If entering multiple values for this property, separate each using a semicolon and a space ("; "). Order of values does not matter.</para>
        </customization>
        <customization co="no" dd="p16786coll3">
            <para>When searching for donor or lender in Sephardic Studies Collection Master Catalog, some contributions will be recorded as "Person A via Person B." In that case, Person A is the former owner, and their name belongs in this field.</para>
            <para>When appropriate, search the &lt;a href="https://id.loc.gov/authorities/names.html"&gt;Library of Congress Name Authority File&lt;/a&gt; via id.loc.gov for the lender name.</para>
            <para>If a potential match is found, confirm that it is the person associated with the resource: it may be helpful to review information included in the web display such as source(s) of information and occupation (for persons), and/or to follow the links provided for exact and/or closely matching concepts from other schemes.</para>
            <para>Copy the name string for use just as it appears at the top of the page, above the URI(s), including dates.</para>
            <para>If no record exists, record personal names as "Lastname, Firstname".</para>
            <para>For a personal name like Alexander Ben Guiat, "Ben" is considered part of the first name and is transcribed as: "Guiat, Alexander Ben".</para>
            <para>If entering multiple values for this property, separate each using a semicolon and a space ("; "). Order of values does not matter.</para>
        </customization>
    </descriptions>
    <examples>
        <example co="object">
            <para>Benezra, Henry</para>
        </example>
        <example co="no">
            <para>Benezra, Henry</para>
        </example>
    </examples>
    <!-- Omit:
        additionalInfo
        marc -->
    <additionalInfo/>
    <marc>
        <dcgMarcMapping/>
    </marc>
    <!-- BMR TO DO: XSD -->
    <xsd/>
    <!-- Omit:
        rdf
        cdmRdf -->
    <rdf/>
    <history>
        <dateCreated>
            <single>2021-03-21</single>
        </dateCreated>
        <created4Coll>Sephardic Studies Digital Collection (p16786coll3)</created4Coll>
        <justification>SSDC requires a property to provide former owner name values.</justification>
        <changeLog>
            <change/>
        </changeLog>
    </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/locationDepicted.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
   <labels>
      <platformIndependent>locationDepicted</platformIndependent>
      <dc>spatial</dc>
   </labels>
   <uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Location Depicted</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>yes</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>The spatial characteristics of the intellectual content of the resource. </para>
         <para>Spatial coverage refers to a physical region.</para>
      </definition>
      <instructions co="no">
         <para>Enter Country--State or Province--City.</para>
         <para>Places names are derived from the LC Authority File.</para>
      </instructions>
      <instructions co="object">
         <para>Enter Country--State or Province--City.</para>
         <para>Places names are derived from the LC Authority File.</para>
      </instructions>
   </descriptions>
   <examples>
      <example co="no">
         <para>United States--Washington (State)—Seattle</para>
         <para>United States--Alaska—Fort Yukon</para>
         <para>Canada—Yukon—Dawson </para>
         <para>Croatia--Zagreb [use current form, even though Yugoslavia was the name when the photo was taken]</para>
         <para>Russia (Federation)--Leningradskaia oblast--Saint Petersburg [use current form, even though it was called Leningrad in Soviet Union, when photo was taken]</para>
      </example>
      <example co="object">
         <para>United States--Washington (State)—Seattle</para>
         <para>United States--Alaska—Fort Yukon</para>
         <para>Canada—Yukon—Dawson </para>
         <para>Croatia--Zagreb [use current form, even though Yugoslavia was the name when the photo was taken]</para>
         <para>Russia (Federation)--Leningradskaia oblast--Saint Petersburg [use current form, even though it was called Leningrad in Soviet Union, when photo was taken]</para>
      </example>
      <customization co="no" dd="neareast">
         <para>Egypt</para>
         <para>Egypt--Alexandria</para>
         <para>Egypt--Cairo--Jizah</para>
         <para>Egypt--Dayr al-Bahri Site</para>
         <para>Egypt--Nile River Delta</para>
         <para>Israel--West Bank--Jericho</para>
      </customization>
   </examples>
   <additionalInfo/>
   <marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc>
   <xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd>
   <rdf>
      <sameAs/>
   </rdf>
   <history>
      <dateCreated>
         <range>
            <start>2000-01-01</start>
            <end>2017-01-06</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Photograph Collections</created4Coll>
      <justification>We wanted a property dedicated to describing the location depicted in an image.</justification>
      <changeLog>
         <change/>
         <change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
      </changeLog>
   </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/digitalFormat.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd"><uid>p29</uid><labels>
      <platformIndependent>digitalFormat</platformIndependent>
      <dc>format</dc>
   </labels><uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired><cdm>
      <label>Digital Format</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm><dspace>
      <dspaceProperty/>
   </dspace><descriptions>
      <definition>
         <para>File format of a digital resource.</para>
      </definition>
      <instructions co="item">
         <para>Enter the file format of the access item.</para>
         <para>Use media types listed at http://www.iana.org/assignments/media-types/index.html</para>
         <para>For audio WAVE files, enter audio/wav.</para>
      </instructions>
      <instructions co="no">
         <para>Enter the file format of the access item.</para>
         <para>Use media types listed at http://www.iana.org/assignments/media-types/index.html</para>
         <para>For audio WAVE files, enter audio/wav.</para>
      </instructions>
   </descriptions><examples>
      <example co="item">
         <para>audio/mpeg</para>
         <para>image/jpeg</para>
         <para>application/pdf</para>
         <para>text/plain</para>
      </example>
      <example co="no">
         <para>audio/mpeg</para>
         <para>image/jpeg</para>
         <para>application/pdf</para>
         <para>text/plain</para>
      </example>
   </examples><additionalInfo/><marc>
      <dcgMarcMapping/>
      <marcNotes>
         <para/>
      </marcNotes>
   </marc><xsd>
      <typeInfo level="item">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
   </xsd>
   <rdf>
   <owlDatatypeProperty>yes</owlDatatypeProperty>
   </rdf>
   <history>
      <dateCreated>
         <single>2012-01-01</single>
      </dateCreated>
      <created4Coll>Special Collections Oral Histories Collections</created4Coll>
      <justification>Special Collections wanted a place to describe the file format of the service copy of the resource..</justification>
      <changeLog>
         <change date="2019-04-22">Added instructions and example for @co="no"</change>
         <change date="2019-05-20">//rdf/owlDatatypeProperty='yes' to push into DCMI 1.1 namespace.</change>
      </changeLog>
      
   </history></property>
