=== UniverityOfWashingtonLibrariesSchemas/schemasProject/xsd4md/schema-4-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    targetNamespace="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md">
    
    <!-- vresion 0.1 2017-07-26 -->

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>
    
    <xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="https://www.w3.org/2001/XMLSchema.xsd"/>

    <xs:annotation>
        <xs:documentation>Schema to validate properties used by UW Libraries.</xs:documentation>
    </xs:annotation>

    <xs:element name="property" type="propertyType">
    </xs:element>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="labels" type="labelType"/>
            <xs:element name="cdm" type="cdmType"/>
            <xs:element name="dspace" type="dspaceType"/>
            <xs:element name="descriptions" type="descriptionsType"/>
            <xs:element name="examples" type="examplesType"/>
            <xs:element name="additionalInfo" type="additionalInfoType"/>
            <xs:element name="marc" type="marcType"/>
            <xs:element name="xsd" type="xsdType"/>
            <xs:element name="rdf" type="rdfType"/>
            <xs:element name="history" type="historyType"/>
        </xs:sequence>
        <xs:attribute ref="xml:base"/>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:sequence>
            <xs:element name="platformIndependent" type="xs:string"/>
            <xs:element name="dc" type="dcterms"/>
            <xs:element name="dcNotEng" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="language"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cdmType">
        <xs:sequence>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="exportLabel" minOccurs="0" type="xs:string"/>
            <xs:element name="cdmDatatype" type="cdmDatatypeType"/>
            <xs:element name="cdmLarge" type="yesNo"/>
            <xs:element name="searchable" type="yesNo"/>
            <xs:element name="hidden" type="yesNo"/>
            <xs:element name="required" type="yesNo"/>
            <xs:element name="cdmControlledVocab" type="yesNo"/>
        </xs:sequence>
    </xs:complexType>

    <!-- We'll want an enumeration of DSpace properties for use with the dspaceProperty element -->
    <xs:complexType name="dspaceType">
        <xs:sequence>
            <xs:element name="dspaceProperty" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="descriptionsType">
        <xs:sequence>
            <xs:element name="definition" type="paraType" maxOccurs="unbounded"/>
            <xs:element name="instructions" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="examplesType">
        <xs:sequence>
            <xs:element name="example" type="paraType4co" maxOccurs="unbounded"/>
            <xs:element ref="customization" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Note on "admin:"
     any info to help administer the metadata;
     inputting assistance goes in desciptions/instructions;
     further assistance "understanding" the metadata: "generalNotes"-->
    <xs:complexType name="additionalInfoType">
        <xs:sequence>
            <!-- Originally thought 2 elements needed in this sequence;
                 as work progressed, it seemed one was better;
                 recommended: do not use <admin>, use <generalNotes> ;
                 both will be retained to validate legacy data;
                 XSLTs should output both elements as if they were the same-->
            <xs:element name="admin" type="paraType4co" minOccurs="0"/>
            <xs:element name="generalNotes" type="paraType4co" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="marcType">
        <xs:sequence>
            <xs:element name="dcgMarcMapping" type="dcgType"/>
            <xs:element name="dcgNotes" type="paraType" minOccurs="0"/>
            <xs:element name="marcNotes" type="paraType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dcgType">
        <xs:sequence>
            <xs:element name="field" type="xs:integer" minOccurs="0"/>
            <xs:element name="subfield" type="xs:string" minOccurs="0"/>
            <xs:element name="indicators" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="xsdType">
        <xs:sequence>
            <xs:element name="typeAttribute" type="xs:QName" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="simpleType" type="xs:localSimpleType" minOccurs="0"/>
            <xs:element name="complexType" type="xs:localComplexType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="simpleTypeType">
        <xs:sequence>
            <xs:element name="pattern" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

   <!-- might need other properties in addition to sameAs
        like maybe skos:exactMatch, etc.
   -->
    <xs:complexType name="rdfType">
        <xs:sequence>
            <xs:element name="sameAs" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="historyType">
        <xs:sequence>
            <xs:element name="dateCreated">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="single" type="xs:date"/>
                        <xs:element name="range">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="start" type="xs:date"/>
                                    <xs:element name="end" type="xs:date"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="created4Coll" type="xs:string"/>
            <!-- justification needs to be a type=para -->
            <xs:element name="justification" type="xs:string"/>
            <xs:element name="changeLog">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="change">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="date" type="xs:date"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="dcterms">
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="abstract"/>
            <xs:enumeration value="accessRights"/>
            <xs:enumeration value="accrualMethod"/>
            <xs:enumeration value="accrualPeriodicity"/>
            <xs:enumeration value="accrualPolicy"/>
            <xs:enumeration value="alternative"/>
            <xs:enumeration value="audience"/>
            <xs:enumeration value="available"/>
            <xs:enumeration value="bibliographicCitation"/>
            <xs:enumeration value="conformsTo"/>
            <xs:enumeration value="contributor"/>
            <xs:enumeration value="coverage"/>
            <xs:enumeration value="created"/>
            <xs:enumeration value="creator"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateAccepted"/>
            <xs:enumeration value="dateCopyrighted"/>
            <xs:enumeration value="dateSubmitted"/>
            <xs:enumeration value="description"/>
            <xs:enumeration value="educationLevel"/>
            <xs:enumeration value="extent"/>
            <xs:enumeration value="format"/>
            <xs:enumeration value="hasFormat"/>
            <xs:enumeration value="hasPart"/>
            <xs:enumeration value="hasVersion"/>
            <xs:enumeration value="identifier"/>
            <xs:enumeration value="instructionalMethod"/>
            <xs:enumeration value="isFormatOf"/>
            <xs:enumeration value="isPartOf"/>
            <xs:enumeration value="isReferencedBy"/>
            <xs:enumeration value="isReplacedBy"/>
            <xs:enumeration value="isRequiredBy"/>
            <xs:enumeration value="issued"/>
            <xs:enumeration value="isVersionOf"/>
            <xs:enumeration value="language"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="mediator"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="modified"/>
            <xs:enumeration value="provenance"/>
            <xs:enumeration value="publisher"/>
            <xs:enumeration value="references"/>
            <xs:enumeration value="relation"/>
            <xs:enumeration value="replaces"/>
            <xs:enumeration value="requires"/>
            <xs:enumeration value="rights"/>
            <xs:enumeration value="rightsHolder"/>
            <xs:enumeration value="source"/>
            <xs:enumeration value="spatial"/>
            <xs:enumeration value="subject"/>
            <xs:enumeration value="tableOfContents"/>
            <xs:enumeration value="temporal"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="valid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cdmDatatypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="fullText"/>
            <xs:enumeration value="cdmAdministrative"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="yesNo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paraType">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="paraType4co">
        <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="co" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="no"/>
                    <xs:enumeration value="object"/>
                    <xs:enumeration value="item"/>
                <!-- the following 3 types of COs eliminated 2017-06-29;
                     we may want them for generalNotes however:
                    <xs:enumeration value="objectAndStandalone"/>
                    <xs:enumeration value="itemAndStandalone/"/>
                    <xs:enumeration value="coAll"/>-->
                    <xs:enumeration value="all"/>
                    <xs:enumeration value="agnostic"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- below global attribute does not seem necessary
    <xs:attribute name="co">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="no"/>
                <xs:enumeration value="object"/>
                <xs:enumeration value="item"/>
                <xs:enumeration value="coAll"/>
                <xs:enumeration value="all"/>
                <xs:enumeration value="agnostic"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    -->

    <xs:element name="customization" type="custParaType"/>

    <xs:complexType name="custParaType">
        <xs:complexContent>
            <xs:extension base="paraType4co">
                <xs:attribute name="dd" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="exPara"/>

</xs:schema>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/institution.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
    <labels>
        <platformIndependent>institution</platformIndependent>
        <dc>provenance</dc>
    </labels>
    <cdm>
        <label>Institution</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>yes</searchable>
        <hidden>yes</hidden>
        <cdmRequired>no</cdmRequired><uwRequired>no</uwRequired>
        <cdmControlledVocab>no</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty/>
    </dspace>
    <descriptions>
        <definition>
            <para>[Uncertain]</para>
        </definition>
        <instructions co="no">
            <para>[Uncertain]</para>
        </instructions>
        <instructions co="object">
            <para>[Uncertain]</para>
        </instructions>
        <instructions co="item">
            <para>[Uncertain]</para>
        </instructions>
        
    </descriptions>
    <examples>
        <example co="no">
            <para>[none]</para>
        </example>
        
        <!-- customization here is flawed.
             I think we need
             <customizations>
                 <description | example>
                     <para @co @dd @paraDec @paraEx> REPEATABLE
                         <para>
        -->
        
    </examples>
    <additionalInfo>
        <admin co="all">
            <para>Seems to be a DI/ITS admin field.</para>
            <para>For use with CONTENTdm "facets?"</para>
            <para>This is a misuse of the dc:provenance property; we should repair this property?</para>
        </admin>
    </additionalInfo>
    <marc>
        <dcgMarcMapping/>
        <marcNotes>
            <para/>
        </marcNotes>
    </marc>
    <xsd>
        <typeAttribute>xs:string</typeAttribute>
        <complexType/>
    </xsd>
    <rdf>
        <sameAs/>
    </rdf>
    <history>
        <dateCreated>
            <range>
                <start>2000-01-01</start>
                <end>2015-02-21</end>
            </range>
        </dateCreated>
        <created4Coll>Alaska Yukon Pacific Exposition Photographs</created4Coll>
        <justification>[Uncertain]</justification>
        <changeLog>
            <change/><change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
        </changeLog>
    </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/interviewer.xml
<?xml version="1.0" encoding="UTF-8"?><property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd"><uid>p47</uid><labels>
      <platformIndependent>interviewer</platformIndependent>
      <dc>creator</dc>
   </labels><uwRequired>
      <uwStandalone>yes</uwStandalone>
      <uwObject>yes</uwObject>
      <uwItem>no</uwItem>
   </uwRequired><cdm>
      <label>Interviewer</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm><dspace>
      <dspaceProperty/>
   </dspace><descriptions>
      <definition>
         <para>The person who interviewed the interviewee.</para>
      </definition>
      <instructions co="no">
         <para>Enter the name of the person who interviewed the subject.</para>
         <para>Format of personal name: Lastname, Firstname.</para>
         <para>Use LC Name Authority File for form of name when available: http://authorities.loc.gov or http://id.loc.gov/</para>
         <para>Separate multiple values with a semi-colon.</para>
      </instructions>
      <instructions co="object">
         <para>Enter the name of the person who interviewed the subject.</para>
         <para>Format of personal name: Lastname, Firstname.</para>
         <para>Use LC Name Authority File for form of name when available: http://authorities.loc.gov or http://id.loc.gov/</para>
         <para>Separate multiple values with a semi-colon.</para>
      </instructions>
   </descriptions><examples>
      <example co="object">
         <para>Kinsey, Clark</para>
         <para>Daiber, Ome</para>
         <para>Daiber, Ome; Armstrong, Calvin</para>
         <para>Colbert, Curt, 1947- </para>
         <para>Boeing Company. Boeing Military Aircraft and Missile Systems Group</para>
      </example>
      <example co="all">
         <para>Boyd and Braas</para>
      </example>
      <customization co="no" dd="neareast">
         <para>Noegel, Scott B.</para>
      </customization>
      <customization co="object" dd="uwtoh">
         <para>Williams, Charles</para>
         <para>Meyers, Richard D.</para>
         <para>Colbert, Curt, 1947-</para>
      </customization>
   </examples><additionalInfo/><marc>
      <dcgMarcMapping/>
      <marcNotes/>
   </marc><xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd><rdf>
      <sameAs/>
   </rdf><history>
      <dateCreated>
         <range>
            <start>2012-01-01</start>
            <end>2018-03-21</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Oral History Collections</created4Coll>
      <justification>Every oral history that involves an interview has an interviewer. Special Collections believed the interview should be described and indexed./</justification>
      <changeLog>
         <change/>
      </changeLog>
   </history></property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/date.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
    <labels>
        <platformIndependent>dateCreated</platformIndependent>
        <dc>created</dc>
        <!-- I don't think we need schemaLabel; shemas are to be produced for validating cdm exports; look at thos exports and see how the property labels export; the cdmLabel might be adequate for producing the schema -->
    </labels>
    <cdm>
        <label>Date</label>
        <cdmDatatype>text</cdmDatatype>
        <cdmLarge>no</cdmLarge>
        <searchable>no</searchable>
        <hidden>no</hidden>
        <cdmRequired>no</cdmRequired>
        <uwRequired>yes</uwRequired>
        <cdmControlledVocab>no</cdmControlledVocab>
    </cdm>
    <dspace>
        <dspaceProperty/>
    </dspace>
    <descriptions>
        <definition>
            <para>Date of creation of the resource.</para>
            <para>If the resource is a photograph, the date the original photograph was taken.</para>
            <para>In cases where a painting, engraving, or architectural drawing was photographed, the date the artwork was created.</para>
        </definition>
        <instructions co="no">
            <para>If the date when the image/resource in hand was produced is known, and is different from that of the original image, so note in the Notes field. The date should be a specific year. If the date is unknown, an attempt should be made to assign an approximate date, using the form "ca." (circa).</para>
            <para>In CONTENTdm, this field is used for display purposes and should be user-friendly. The Dates field is indexed, enabling searching (see that entry for details). Specific dates (e.g., September 12, 1933; June 1912) should be entered in this field, and should also be incorporated in the Title field.</para>
            <para>Date value should agree with date values entered in Date-Edtf and Dates fields.</para>
            <para>If the date is a single year, enter the date in the following format: YYYY</para>
            <para>If the date is a month and a year, enter name-of-month, YYYY</para>
            <para>If the date is a month, day and year, enter name-of-month number-of-day, YYYY</para>
            <para>If the date is a known date range, enter the two dates as above, separated with a dash</para>
            <para>If the date between a date range or an approximate date, the date should be qualified with either the word "between" or "approximately."</para>
        </instructions>
        <instructions co="object">
            <para>If the date when the image/resource in hand was produced is known, and is different from that of the original image, so note in the Notes field. The date should be a specific year. If the date is unknown, an attempt should be made to assign an approximate date, using the form "ca." (circa).</para>
            <para>In CONTENTdm, this field is used for display purposes and should be user-friendly. The Dates field is indexed, enabling searching (see that entry for details). Specific dates (e.g., September 12, 1933; June 1912) should be entered in this field, and should also be incorporated in the Title field.</para>
            <para>Date value should agree with date values entered in Date-Edtf and Dates fields.</para>
            <para>If the date is a single year, enter the date in the following format: YYYY</para>
            <para>If the date is a month and a year, enter name-of-month, YYYY</para>
            <para>If the date is a month, day and year, enter name-of-month number-of-day, YYYY</para>
            <para>If the date is a known date range, enter the two dates as above, separated with a dash</para>
            <para>If the date between a date range or an approximate date, the date should be qualified with either the word "between" or "approximately."</para>
        </instructions>
    </descriptions>
    <examples>
        <example co="no">
            <para>1940</para>
            <para>May, 2001</para>
            <para>May 9, 2001</para>
            <para>1946-1952</para>
            <para>May 2, 1946-June 4, 1952</para>
            <para>Between 1910 and 1923</para>
            <para>Approximately 1930</para>
        </example>
        <example co="object">
            <para>1940</para>
            <para>May, 2001</para>
            <para>May 9, 2001</para>
            <para>1946-1952</para>
            <para>May 2, 1946-June 4, 1952</para>
            <para>Between 1910 and 1923</para>
            <para>Approximately 1930</para>
        </example>
    </examples>
    <additionalInfo/>
    <marc>
        <dcgMarcMapping/>
        <marcNotes/>
    </marc>
    <xsd>
        <simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
            </xs:restriction>
        </simpleType>
    </xsd>
    <rdf>
        <sameAs/>
    </rdf>
    <history>
        <dateCreated>
            <range>
                <start>2000-01-01</start>
                <end>2016-11-10</end>
            </range>
        </dateCreated>
        <created4Coll>Special Collections Photograph Collections</created4Coll>
        <justification>We need a display dates field that will be easy for users to understand. It does not need to be indexed but it seems OK to map to Dublin Core.</justification>
        <changeLog>
            <change/>
            <change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation. Also added instruction.</change>
        </changeLog>
    </history>
</property>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/properties-files/author.xml
<?xml version="1.0" encoding="UTF-8"?>
<property xmlns="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xsi:schemaLocation="http://faculty.washington.edu/tgis/schemasProject/xsd4md http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-properties.xsd">
   <uid>p6</uid>
   <labels>
      <platformIndependent>author</platformIndependent>
      <dc>creator</dc>
   </labels>
   <uwRequired>
      <uwStandalone>no</uwStandalone>
      <uwObject>no</uwObject>
      <uwItem>no</uwItem>
   </uwRequired>
   <cdm>
      <label>Author</label>
      <cdmDatatype>text</cdmDatatype>
      <cdmLarge>no</cdmLarge>
      <searchable>yes</searchable>
      <hidden>no</hidden>
      <cdmRequired>no</cdmRequired>
      <cdmControlledVocab>no</cdmControlledVocab>
   </cdm>
   <dspace>
      <dspaceProperty/>
   </dspace>
   <descriptions>
      <definition>
         <para>The person or the corporate body responsible for the textual content.</para>
      </definition>
      <instructions co="no">
         <para>Input lastname, firstname or the corporate body name.</para>
         <para>Use LC Authority File for form of name, if available.</para>
         <para>Multiple names are okay; separate multiple names with a semi-colon.</para>
         <para>If the Creator is determined from a resource other than the item, create a Note.</para>
         <para>If there is no author, leave the field blank.</para>
      </instructions>
      <instructions co="object">
         <para>Input lastname, firstname or the corporate body name.</para>
         <para>Use LC Authority File for form of name, if available.</para>
         <para>Multiple names are okay; separate multiple names with a semi-colon.</para>
         <para>If the Creator is determined from a resource other than the item, create a Note.</para>
         <para>If there is no author, leave the field blank.</para>
      </instructions>
      <customization co="object" dd="ssdc">
         <para>Search for author name in Library of Congress Name Authority File; if record exists, transcribe name as it appears in the name authority file, including dates.</para>
         <para>If no record exists, transliterate author name on title page using LOC rules.</para>
         <para>Author names usually appear on title page after the following designations: el autor; kompuesto; por.</para>
      </customization>
   </descriptions>
   <examples>
      <example co="all">
         <para>Strong, Lyman W.</para>
      </example>
      <customization co="object" dd="ssdc">
         <para>Saint-Pierre, Bernardin de, 1737-1814.</para>
      </customization>
   </examples>
   <additionalInfo/>
   <marc>
      <dcgMarcMapping/>
      <marcNotes/>
   </marc>
   <xsd>
      <typeInfo level="standalone object">
         <typeAttribute>xs:string</typeAttribute>
      </typeInfo>
      <typeInfo level="item">
         <empty/>
      </typeInfo>
   </xsd>
   <rdf>
      <!-- no RDF info yet for author -->
   </rdf>
   <history>
      <dateCreated>
         <range>
            <start>2000-01-01</start>
            <end>2017-06-29</end>
         </range>
      </dateCreated>
      <created4Coll>Special Collections Civil War Letters Collection, and Special Collections Pamphlet and Textul Collection</created4Coll>
      <justification>Wanted a way to distinguish authors of text.</justification>
      <changeLog>
         <change/>
         <change date="2017-10-23">changed //cdm/required to //cdm/cdmRequired and //cdm/uwRequired to assist in halting use of the cdm "required" feature while, at the same time, indicating that UW-cdm collections must use, or not use, a given property; also changed @xsi:schemaLocation.</change>
      </changeLog>
   </history>
</property>
