=== UniverityOfWashingtonLibrariesSchemas/schemasProject/xsd4md/schema-4-dds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:props="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
    targetNamespace="http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries"
    xmlns="http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries">
    
    <!-- version 0.3 2017-26 -->

    <xs:import namespace="http://faculty.washington.edu/tgis/schemasProject/xsd4md"
         schemaLocation="schema-4-properties.xsd"/>

    <!-- Note from TG, 2015-12-10: I attempted to make the default namespace
    http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries
    but that made my references to global types unusable, I'm not sure why.
    This can be resolved at a future date; for now I've fallen back to noNamespace.
    -->

    <xs:annotation>
        <xs:documentation> This is a schema to validate MIG data dictionaries. The MIG data
            dictionaries were written to guide CONTENTdm collection configurations and metadata input. The
            official version of those data dictionaries are posted at
            http://www.lib.washington.edu/msd/pubcat/mig/datadicts. MIG maintains a source XML file
            for selected data dictionaries (as of 2015-12-10), which is an XML file that can be
            validated using this schema. </xs:documentation>
    </xs:annotation>

    <xs:element name="migDataDictionary" type="ddType"/>

    <xs:complexType name="ddType">
        <xs:sequence>
            <xs:element name="ddName" type="xs:string"/>
            <xs:element name="ddPartOfProject" type="xs:string"/>
            <xs:element name="originalCreationDate" type="xs:date"/>
            <xs:element name="latestUpdate" type="xs:date"/>
            <xs:element name="metadataLiaisons">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="metadataLiaison" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cdmCo" type="props:yesNo">
                <xs:annotation>
                    <xs:documentation>Element for recording whether or not CONTENTdm compound objects are permitted.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="standalone" type="props:yesNo">
                <xs:annotation>
                    <xs:documentation>Element for recording whether or not CONTENTdm compound objects are permitted. Needed to state whether standalone can co-exist with compound objects.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="suppressItemProp" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Element for enumerating the name of any property listed in the xml data dictionary that should not be output to the item description in the authoritative data dictionary. This happens because different projects are selective about what properties can go into the item description; just because we list it in the xml data dictionary for use in the object or standalone data dictionary, does not necessarily mean it is going into the item description, but those properties that have @co="item" will be output into the authoritative dictionary. This element allows us to suppress those properties as needed. To do this, the value at /property/labels/platformIndependant should be used as the value of the suppressItemProp element.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="cdmCode" type="xs:string"/>
            <xs:element name="properties"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
</xs:schema>

=== UniverityOfWashingtonLibrariesSchemas/schemasProject/dataDictionaries/xml/greekDances-dd.xml
<?xml version="1.0" encoding="UTF-8"?>
<migDataDictionary xmlns="http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries"
    xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    id="0001"
    xsi:schemaLocation="http://www.lib.washington.edu/msd/mig/schemas/dataDictionaries http://faculty.washington.edu/tgis/schemasProject/xsd4md/schema-4-dds.xsd">
    <ddName>Greek Dances Videos</ddName>
    <ddPartOfProject/>
    <originalCreationDate>2020-03-24</originalCreationDate>
    <latestUpdate>2020-03-24</latestUpdate>
    <metadataLiaisons>
        <metadataLiaison>TBD</metadataLiaison>
    </metadataLiaisons>
    <cdmCo>yes</cdmCo>
    <standalone>no</standalone>
    <cdmCode>dances</cdmCode>
    <properties>
        <xi:include href="../../properties-files/title.xml"/>
    </properties>
</migDataDictionary>
